/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Notas.java
 *
 * Created on Mar 3, 2011, 9:42:09 AM
 */
package org.fabnun.senu;

import java.awt.Component;
import java.awt.Dimension;
import java.util.List;
import javax.swing.JOptionPane;
import org.fabnun.senu.vista.FocusInterface;

/**
 *
 * @author fabnun
 */
public class Notas extends javax.swing.JPanel implements FocusInterface {

    public void KeyPressed(int keyCode, int modif) {
    }
    private String usuario;

    public void setUsuario(String usuario) {
        this.usuario = usuario;
        jTabbedPane1.removeAll();
        try {
            List<Object[]> notas = Constantes.db.getNotas(usuario);
            for (Object[] datos : notas) {
                jTabbedPane1.add(datos[0].toString(), new NotaConfig(datos, jToggleButton1.isSelected(), editarNotas));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    boolean editarNotas;

    /** Creates new form Notas */
    public Notas(boolean editarNotas) {
        initComponents();
        this.editarNotas = editarNotas;
        jToolBar1.setVisible(editarNotas);
        setPreferredSize(new Dimension(640, 480));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));
        add(jTabbedPane1);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setMaximumSize(new java.awt.Dimension(2048, 31));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/fabnun/senu/iconos/accessories-text-editor.png"))); // NOI18N
        jButton1.setText("Nueva Nota");
        jButton1.setFocusable(false);
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/fabnun/senu/iconos/dialog-warning.png"))); // NOI18N
        jButton2.setText("Eliminar Nota");
        jButton2.setFocusable(false);
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton2.setMaximumSize(new java.awt.Dimension(100, 29));
        jButton2.setMinimumSize(new java.awt.Dimension(100, 29));
        jButton2.setPreferredSize(new java.awt.Dimension(100, 29));
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);
        jToolBar1.add(jPanel1);

        jToggleButton1.setText("Configurar Nota");
        jToggleButton1.setFocusable(false);
        jToggleButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton1.setMaximumSize(new java.awt.Dimension(100, 29));
        jToggleButton1.setMinimumSize(new java.awt.Dimension(100, 29));
        jToggleButton1.setPreferredSize(new java.awt.Dimension(100, 29));
        jToggleButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButton1);

        add(jToolBar1);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String titulo = JOptionPane.showInputDialog("Titulo de la Nota?", "");
        if (titulo != null) {
            try {
                Constantes.db.nuevaNota(titulo, usuario, "", -1646052, -16777216, null, 0, "1", "");
                Object[] datos = new Object[]{
                    titulo, usuario, "", -1646052, -16777216, null, 0, "1", ""
                };
                jTabbedPane1.add(titulo, new NotaConfig(datos, jToggleButton1.isSelected(), editarNotas));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Existe una nota con el mismo titulo");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int idx = jTabbedPane1.getSelectedIndex();
        String titulo = jTabbedPane1.getTitleAt(idx);
        if (JOptionPane.showConfirmDialog(this, "Desea eliminar la nota: " + titulo + "?", "Eliminar Nota", JOptionPane.YES_NO_OPTION) == 0) {
            try {
                Constantes.db.eliminarNota(titulo, usuario);
                jTabbedPane1.remove(idx);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al eliminar nota");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        int size = jTabbedPane1.getComponentCount();
        boolean selected = jToggleButton1.isSelected();
        for (int i = 0; i < size; i++) {
            NotaConfig nt = (NotaConfig) jTabbedPane1.getComponent(i);
            nt.setConfigVisible(selected);
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

    public Component[][] getFocus() {
        return null;
    }
}
